##LINEAR REGRESSION

In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

# Generate some sample data
# Let's say we are predicting 'y' based on 'x'
np.random.seed(42)

# x will be a 2D array with 100 samples and 1 feature
x = np.random.rand(100, 1) * 10  # Random values between 0 and 10

# y will be a linear function of x with some noise
y = 3 * x.flatten() + np.random.randn(100) * 2  # y = 3 * x + noise

# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Create and train the Linear Regression model
LR = LinearRegression()
ModelLR = LR.fit(x_train, y_train)

# Predict on the test data
PredictionLR = ModelLR.predict(x_test)

# Print the predictions
print("Predictions:", PredictionLR)

# Optional: Print the Mean Squared Error (MSE) to evaluate the model
mse = mean_squared_error(y_test, PredictionLR)
print(f"Mean Squared Error: {mse}")


Predictions: [ 2.14155852 26.41236443 22.83328469 19.62968497  7.84150201 13.13708868
  8.81566002 25.48611166  0.88683818 11.22138484 12.89745261 18.02449268
 24.09509422 27.99071724  3.77765507  4.84114885 22.80483419  2.44773015
 24.59089968  5.26466972]
Mean Squared Error: 2.614798054868012


In [2]:
from sklearn.metrics import r2_score
print('===================LR Testing Accuracy================')
teachLR = r2_score(y_test, PredictionLR)
testingAccLR = teachLR * 100
print(testingAccLR)

===================LR Testing Accuracy================
96.86345415489114


##SUPPORT VECTOR MACHINE

In [5]:
from sklearn import datasets
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Load dataset
iris = datasets.load_iris()
X = iris.data
y = iris.target
y = (y == 0).astype(int)  # Convert to binary classification problem

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Train SVM model with RBF kernel
svm = SVC(kernel='rbf', C=1, gamma='scale')
svm.fit(X_train, y_train)

# Make predictions
y_pred = svm.predict(X_test)

# Evaluate the model
print("SVM Accuracy:", accuracy_score(y_test, y_pred))


SVM Accuracy: 1.0


##DECISION TREE

In [6]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import numpy as np

# Example Data (make sure to define x and y)
# Let's generate some simple data for classification
# x will be random values, and y will be a binary classification target
np.random.seed(42)

# x = 100 samples with 5 features each
x = np.random.rand(100, 5)

# y = binary target with values 0 or 1
y = np.random.randint(0, 2, 100)

# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Initialize the DecisionTreeClassifier
DT = DecisionTreeClassifier()

# Train the model
ModelDT = DT.fit(x_train, y_train)

# Model Testing (Prediction)
PredictionDT = DT.predict(x_test)
print("Predictions:", PredictionDT)

# Model Training Accuracy
print('====================DT Training Accuracy===============')
tracDT = DT.score(x_train, y_train)  # The score method gives accuracy directly
TrainingAccDT = tracDT * 100
print(f"Training Accuracy: {TrainingAccDT:.2f}%")

# Model Testing Accuracy
print('=====================DT Testing Accuracy=================')
teacDT = accuracy_score(y_test, PredictionDT)
testingAccDT = teacDT * 100
print(f"Testing Accuracy: {testingAccDT:.2f}%")


Predictions: [1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
====================DT Training Accuracy===============
Training Accuracy: 100.00%
=====================DT Testing Accuracy=================
Testing Accuracy: 55.00%


In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_test, y_test, test_size=0.1, random_state=42)

ValueError: Found input variables with inconsistent numbers of samples: [150, 100]

In [8]:
from sklearn import datasets
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Load dataset
iris = datasets.load_iris()


In [9]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [10]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [12]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [13]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [14]:
df = ['age', 'gender', 'height', 'weight', 'obese']

In [15]:
X = df['age', 'gender', 'height', 'weight']
y = df['obese']

TypeError: list indices must be integers or slices, not tuple

In [16]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

# Sample data
data = pd.DataFrame({
    'Age': [25, 40, 35, 28,32],
    'Gender': ['Male', 'Female', 'Female', 'Male',None],
    'Education': ['Bachelor', 'High School', 'Master', 'PhD','PhD'],
    'Spending': [70, 40, 65, 80,45]
})

# Ordinal encoding
edu_map = {'High School':1, 'Bachelor':2, 'Master':3, 'PhD':4}
data['Education'] = data['Education'].map(edu_map)



#

# # Clustering
# kmeans = KMeans(n_clusters=2, random_state=42)
# data['Cluster'] = kmeans.fit_predict(scaled)

# print(data)

In [17]:
data

,Age,Gender,Education,Spending
0,25,Male,2,70
1,40,Female,1,40
2,35,Female,3,65
3,28,Male,4,80
4,32,NaN,4,45


In [18]:
# Sample data
data = pd.DataFrame({
    'Age': [25, 40, 35, 28],
    'Gender': ['Male', 'Female', 'Female', 'Male'],
    'Education': ['Bachelor', 'High School', 'Master', 'PhD'],
    'Spending': [70, 40, 65, 80]
})

# Ordinal encoding
edu_map = {'High School':1, 'Bachelor':2, 'Master':3, 'PhD':4}
data['Education'] = data['Education'].map(edu_map)

data
gen_map ={'Male':1,'Female':0}
data['Gender']=data['Gender'].map(gen_map)
data




,Age,Gender,Education,Spending
0,25,1,2,70
1,40,0,1,40
2,35,0,3,65
3,28,1,4,80


In [19]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

# Initialize the MinMaxScaler
scaler = MinMaxScaler()

# Fit and transform the data
scaled_data = scaler.fit_transform(data)

print("Original Data:")
print(np.array(data))
print("\nScaled Data (Range 0-1):")
print(scaled_data)


Original Data:
[[25  1  2 70]
 [40  0  1 40]
 [35  0  3 65]
 [28  1  4 80]]

Scaled Data (Range 0-1):
[[0.         1.         0.33333333 0.75      ]
 [1.         0.         0.         0.        ]
 [0.66666667 0.         0.66666667 0.625     ]
 [0.2        1.         1.         1.        ]]


In [20]:
from sklearn.cluster import KMeans
model = KMeans(n_clusters=2, random_state=42)
data['Cluster'] = model.fit_predict(scaled_data)
data





,Age,Gender,Education,Spending,Cluster
0,25,1,2,70,1
1,40,0,1,40,0
2,35,0,3,65,0
3,28,1,4,80,1


In [21]:
#test model
test_data = pd.DataFrame({
    'Age': [30],
    'Gender': ['Female'],
    'Education': ['Bachelor'],
    'Spending': [75]
})

test_data['Education'] = test_data['Education'].map(edu_map)
test_data['Gender'] = test_data['Gender'].map(gen_map)

test_data =scaler.transform(test_data)
test_data
model.predict(test_data)



array([0], dtype=int32)

In [22]:
model.predict(test_data)[0]

np.int32(0)

In [23]:
df['Age'].fillna(df['Age'].mean(), inplace=True)
mapping = {'Low':1, 'Medium':2, 'High':3}
df['Level'] = df['Level'].map(mapping)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)
df.drop_duplicates(inplace=True)

TypeError: list indices must be integers or slices, not str